version: '3.8'
services:
  jenkins-master:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-overlay-network
    environment:
      - JENKINS_OPTS=--argumentsRealm.passwd.admin=artem
      - JENKINS_OPTS=--argumentsRealm.roles.admin=admin

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  jenkins_home:

networks:
  jenkins-overlay-network:
    external: true

