version: '3.8'
services:
  jenkins-slave:
    image: jenkins/inbound-agent:latest
    privileged: true
    init: true
    networks:
      - jenkins-overlay-network
    environment:
      JENKINS_URL: http://jenkins-master:8080
      JENKINS_SECRET: "{{ agent_secret }}"
      JENKINS_AGENT_NAME: "slave-node-1"
      JENKINS_WEB_SOCKET: true
      DIND: true
      TINI_SUBREAPER: true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  jenkins-overlay-network:
    external: true

